import type { CollectionConfig } from 'payload'

export const Content: CollectionConfig = {
  slug: 'content',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'type', 'status', 'publishedAt'],
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'type',
      type: 'select',
      required: true,
      options: [
        { label: 'Daily Learning', value: 'daily' },
        { label: 'Tutorial', value: 'tutorial' },
        { label: 'Article', value: 'article' },
        { label: 'Tool Focus', value: 'tool-focus' },
        { label: 'Concept Focus', value: 'concept-focus' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'In Review', value: 'review' },
        { label: 'Published', value: 'published' },
        { label: 'Archived', value: 'archived' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'summary',
      type: 'textarea',
      required: true,
    },
    {
      name: 'body',
      type: 'richText',
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'media',
    },
    // Taxonomy
    {
      name: 'domain',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Development', value: 'dev' },
        { label: 'Design', value: 'design' },
        { label: 'Operations', value: 'ops' },
        { label: 'Business', value: 'business' },
        { label: 'AI & Automation', value: 'ai-automation' },
        { label: 'Marketing', value: 'marketing' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'tools',
      type: 'relationship',
      relationTo: 'tools',
      hasMany: true,
    },
    {
      name: 'concepts',
      type: 'text',
      hasMany: true,
      admin: {
        description: 'Concept tags (e.g., "prompt-engineering", "vibe-coding")',
      },
    },
    {
      name: 'complexity',
      type: 'select',
      options: [
        { label: 'Beginner', value: 'beginner' },
        { label: 'Intermediate', value: 'intermediate' },
        { label: 'Advanced', value: 'advanced' },
      ],
      admin: {
        position: 'sidebar',
        condition: (data) => data?.type === 'tutorial',
      },
    },
    {
      name: 'language',
      type: 'select',
      defaultValue: 'fr',
      options: [
        { label: 'Francais', value: 'fr' },
        { label: 'English', value: 'en' },
      ],
      admin: {
        position: 'sidebar',
      },
    },
    // Source tracking
    {
      name: 'source',
      type: 'group',
      admin: {
        position: 'sidebar',
      },
      fields: [
        {
          name: 'type',
          type: 'select',
          options: [
            { label: 'Manual', value: 'manual' },
            { label: 'Notion', value: 'notion' },
            { label: 'CLI', value: 'cli' },
            { label: 'Slack', value: 'slack' },
            { label: 'Browser Extension', value: 'browser' },
            { label: 'Meeting', value: 'meeting' },
          ],
          defaultValue: 'manual',
        },
        {
          name: 'externalId',
          type: 'text',
          admin: {
            description: 'ID from the source system (e.g., Notion page ID)',
          },
        },
      ],
    },
    // Dates
    {
      name: 'publishedAt',
      type: 'date',
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
    },
    // AI metadata
    {
      name: 'aiMetadata',
      type: 'group',
      admin: {
        description: 'Auto-generated by AI enrichment pipeline',
      },
      fields: [
        {
          name: 'qualityScore',
          type: 'number',
          min: 0,
          max: 1,
        },
        {
          name: 'autoTags',
          type: 'text',
          hasMany: true,
        },
        {
          name: 'autoSummary',
          type: 'textarea',
        },
      ],
    },
  ],
}
